import Head from "next/head";
import Intro from "../components/sections/Intro";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admik late clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Intro />
      </main>
    </>
  );
}
